[project]
authors = ["Seth Stadick <sstadick@gmail.com>", "Robert Cocker <https://robertcocker.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Useful things that aren't in the standard library."
name = "ExtraMojo"
version = "0.8.0"
license = "Unlicense OR MIT"
platforms = ["linux-64", "osx-arm64"]

[tasks]
build = "magic run mojo package ExtraMojo -o ExtraMojo.mojopkg"
test = "magic run mojo test test_regex.mojo && mojo run test_file.mojo && magic run mojo test test_bstr.mojo"
format = "magic run mojo format ./"

[dependencies]
max = ">=24.6.0,<25"
